# Generated by Django 4.2.5 on 2023-10-06 00:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bien', models.CharField(max_length=50, unique=True)),
                ('descripcion', models.CharField(max_length=150, unique=True)),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('fecha', models.DateField()),
                ('estado', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grupo_contab', models.CharField(max_length=50, unique=True)),
                ('partida', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Personal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ci', models.PositiveIntegerField()),
                ('nombres', models.CharField(max_length=30, unique=True)),
                ('apellidos', models.CharField(max_length=30, unique=True)),
                ('cargo', models.CharField(max_length=30, unique=True)),
                ('seccion', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Asignar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('bien_activo', models.ManyToManyField(to='activos.activo')),
                ('ci_persona', models.ManyToManyField(to='activos.personal')),
            ],
        ),
        migrations.AddField(
            model_name='activo',
            name='grupo_contab',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activos.grupo'),
        ),
    ]
