# Generated by Django 4.2.5 on 2023-10-06 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activo',
            name='estado',
            field=models.CharField(max_length=20),
        ),
    ]
